# Generated by Django 4.0.3 on 2022-04-19 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_userregistationform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegistationForm',
        ),
    ]
