# Generated by Django 4.0.3 on 2022-04-20 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_createuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateUser',
        ),
    ]
