# Generated by Django 4.0.3 on 2022-04-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_rename_fist_name_userprofilemodlel_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodlel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
