# Generated by Django 4.0.3 on 2022-04-21 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_alter_userprofilemodlel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodlel',
            name='address',
        ),
    ]
