# Generated by Django 4.0.3 on 2022-04-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_userprofilemodlel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodlel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
