# Generated by Django 4.0.3 on 2022-04-21 09:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0014_alter_userprofilemodlel_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfileModlel',
            new_name='UserProfileModel',
        ),
    ]
