# Generated by Django 4.0.3 on 2022-04-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_alter_userprofilemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
