# Generated by Django 4.0.3 on 2022-04-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_alter_userprofilemodel_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
